### PR TITLE
Legacy

### PR DESCRIPTION
**Pull request by dakom**

### CODE REVIEW

**Comment by dakom** [comment]
@MendyBerger this PR _only_ touches the ad-hoc weird stuff in `build-utils`. There may be subsequent PRs which affect the player, so I didn't want to muddy the waters by mixing it all in here

**Comment by MendyBerger** [comment]
@dakom anything in particular that you want me to review?

**Comment by dakom** [comment]
Not really, it's very duct-tape-and-bubblegum temp code I needed for migrations. Not even really a tool to run ever again. But I think it should be kept in the repo just in case

When I get to player changes that may require more careful attention, will give you a heads up when that happens

**Comment by MendyBerger** [comment]
Okay, feel free to merge

**Pull request merged**
