### PR TITLE
feat: remove gray border from iframe

### LINKED ISSUE #1888: Dark gray outlines - Why are you here?
I see these dark gray outlines around the canvas, near the JIG panel, and on top, below the browser panel.
Can we get rid of them?

Screen Shot 2021-11-11 at 14 22 35
k,

### PR DESCRIPTION
**Pull request by mastapegs**
closes #1888 

The gray border was due to the rendered `iframe` element. Removing it required adding the following attribute: `frameBorder="0"`

Image below showing the disappearance of the grey border:
image

### CODE REVIEW

**Review by MendyBerger — CHANGES_REQUESTED** [review]
I think that frameborder is deprecated, can you use css for this?

**Comment by mastapegs** [comment]
Yea, definitely deprecated

Screenshot_20211230-075730

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by mastapegs** [comment]
Hey there @MendyBerger, I've switched out the use of the deprecated attribute `frameBorder`, with the CSS solution of setting `border: none` to the `iframe`

**Review by MendyBerger — CHANGES_REQUESTED** [review]
This approach to CSS is great for cases where multiple elements need to be styled at once, but in this case there are 2 much simpler ways to go about it:

1. use the dominator `.style` method, works similar to `.property`.
2. If the elements parent is a custom element you can style it with `::slotted`.

**Comment by mastapegs** [comment]
Using `.styles` was SO much easier than applying the `LAZY` CSS. Thank you for that advice @MendyBerger 🙏

And dropped the necessary changes down to a single line.

**Pull request merged**
